name: Scrape and Save IOCs

on:
  workflow_dispatch:
    inputs:
      feed_url:
        description: 'Optional: One specific feed URL'
        required: false
      limit:
        description: 'Max IOCs to scrape'
        required: false
        default: '50'
  schedule:
    - cron: '0 1 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Scrape IOCs to CSV
        run: |
          FEED_URL="${{ github.event.inputs.feed_url }}"
          LIMIT="${{ github.event.inputs.limit || 50 }}"
          python scripts/scrape_iocs.py --limit "$LIMIT" ${FEED_URL:+--feed-url "$FEED_URL"}
      
      - name: Commit updated threat feed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f assets/threat-intel/threat-feed.csv
          git commit -m "⬆️ Updated threat feed at $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push

